export const ERRORS = {
    PAUSED: 'Paused',
    INIT_PARAMS_INVALID: 'InitParamsInvalid',
    ROYALTY_TOO_HIGH: 'RoyaltyTooHigh',
    NOT_PROFILE_OWNER: 'NotProfileOwner',
    INITIALIZED: 'Initialized',
    DERIVED_RULEMODULE_NOT_WHITELISTED: 'DerivedRuleModuleNotWhitelisted',
    ENDTIMESTAMP_TOOLARGE: "EndTimeStampTooLarge",
    COLLECTIONID_NOT_EXIST: "CollectionIdNotExist",
    DERIVEDFROM_NFT_NOT_EXIST: "DerivedFromNFTNotExist",
    JUST_OWNERCAN_PUBLISH_ROOT_NODE: "JustOwnerCanPublishRootNode",
    NOT_GOVERNANCE: "NotGovernance",
    NOT_GOVERNANCE_OR_EMERGENCYADMIN: "NotGovernanceOrEmergencyAdmin",
    EMERGENCYADMIN_JUST_CAN_PAUSE: "EmergencyAdminJustCanPause",
    BURN_EXPIRE_ONE_WEEK: "BurnExpiredOneWeek",
    NOT_COLLECTION_OWNER: "NotCollectionOwner",
    MINT_EXPIRED: "MintExpired",
    MINT_LIMIT_EXCEEDED: "MintLimitExceeded",
    MODULE_DATA_MISMATCH: "ModuleDataMismatch",
    NOT_ENOUGH_FUNDS: 'NotEnoughFunds',
    CAN_NOT_DELETE_ZERO_NFT: 'CanNotDeleteZeroNFT',
  };
  